"use client";

import { initializeIconList } from "@/loader/icon";
import "ducduchy-react-components/dist/ducduchy-react-components.cjs.production.min.css";
import { Cinzel } from "next/font/google";
import { AppHeader } from "../components/AppHeader";
import "./globals.scss";

initializeIconList();

const cinzel = Cinzel({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cinzel.className}>
        <AppHeader />

        {children}
      </body>
    </html>
  );
}
